### ISSUE TITLE
check when qr is scanned

### ISSUE THREAD

**Issue by eeyingforgor** [constantoine/totp-rs#43]
Is there any way of checking when the qr code is scanned to run a function afterwards?

**Comment by Amanse** [comment]
the qr code contains only the key, for having a watch there would be a need for some kind of local server, but that wouldn't work unless both devices are on same network

what's the function you have in mind? maybe there can be some other workaround

**Comment by constantoine** [comment]
The QR code is just some kind of special link understood by 2fa applications. There's no way to detect this, as those applications don't send a callback afterwards

Once the user say they have scanned, you want them to send your website the token generated by the newly added 2fa to make sure it got scanned and added properly
