### ISSUE TITLE
question - how to support steam?

### ISSUE THREAD

**Issue by colemickens** [constantoine/totp-rs#45]
Steam Authenticator uses TOTP but with `digits=5`.

Is this something you're interested in supporting, somehow?

**Comment by timvisee** [comment]
I'd love to see this as well!

It's not just digits=5, because the authenticator also shows alphabetic characters.

Here's an example implementation: https://github.com/ran-sama/python-steam-authenticator/blob/master/steam.py

**Comment by constantoine** [comment]
Hi!

I think I see how it would work, but I'm not sure how to expose it without
yet another breaking change... Perhaps a 4rth option of the "Algorithm"
enum? Possibly gated behind a "steam" feature?

This would be the least breaking change.

Obviously URL/QR generation wouldn't work on this algorithm. I have some
implementation ideas. My phone isn't rooted so I can't really test this out

**Comment by colemickens** [comment]
@constantoine Just a small note, I was able to extract my Steam key without using Android (there's a desktop app and it stores the totp secret in a plaintext json file if you opt-out of "encryption". I think there's also a non-root Android method but I haven't tried. (I can't speak to the API changes, not experienced enough with writing Rust libs or using totp-rs to have thoughts!)

I also don't know enough about HOTP/TOTP, but if the Steam implementation of the actual underlying "math" is different, maybe it's not appropriate here, I'm not sure. I was hoping it was "same algorithm just with 5 instead of 6".

**Comment by constantoine** [comment]
@colemickens huh, that's definetly interesting, I didn't know about that

It is actually the same maths, the only difference is once you get a numeric result, the way you display it is just a tad bit different

**Comment by timvisee** [comment]
@constantoine I'd be happy to implement a `Algorithm::Steam` behind a `steam` feature. Should I give that a try?

**Comment by timvisee** [comment]
By the way, I do have a rooted phone. Aegis outputs Steam as:

`otpauth://totp/timvisee?period=30&digits=6&algorithm=SHA1&secret=ABCDEFGHIJKLMNOPQRSTUVWXYZ234567&issuer=Steam`

**Comment by timvisee** [comment]
By the way, I do have a rooted phone. Aegis outputs Steam as:

`otpauth://steam/Steam%3Atimvisee?period=30&digits=5&algorithm=SHA1&secret=ABCDEFGHIJKLMNOPQRSTUVWXYZ234567&issuer=Steam`

**Comment by constantoine** [comment]
The Issuer:AccountName part is nice/standard, so that won't be a problem

**Comment by timvisee** [comment]
> The Issuer:AccountName part is nice/standard, so that won't be a problem

Usage of `:` is currently prevented by this:

https://github.com/constantoine/totp-rs/blob/d460bd229d76b34f9d38b1c8e9472d898b994615/src/lib.rs#L265-L267

I'll remove that then.

**Comment by constantoine** [comment]
I see the confusion

When instanciating from the API, the lib asks for an Issuer and an AccountName

When parsing from a URL, it will need to be in the form of

otpauth://totp/Issuer:AccountName?issuer=Issuer

**Comment by timvisee** [comment]
It seems that the account name is commonly encoded using URL encoding, which would mean it can contain a `:` as `%3A`, which is also what you see here: https://github.com/constantoine/totp-rs/issues/45#issuecomment-1369175366

**Comment by constantoine** [comment]
Hey @colemickens @timvisee, just a quick ping to tell you v4.1 has been released :)
