### ISSUE TITLE
Adding support for parsing URL of `otpauth-migration`

### ISSUE THREAD

**Issue by NMZ0429** [constantoine/totp-rs#70]
## Summary

- The crate has an ability to read `otpauth` URL but not `otpauth-migration` which is used to transfer existing TOTP account from authenticator such as Google Auth. Adding support for that type of URL is useful for those who want to develop authenticator in Rust and give the ability to transfer existing account to it.
- I would like to know if there is a demand for such feature before contributing to the repository.

## Possible Implementation

- The format of the URL is `otpauth-migration://offline?data=BASE64STRING...` and simply parsing the base64 encoded string with protobuf extracts all information such as issuer and secret key. The definition needed by the protobuf is provided unofficially by some authenticator app like [this](app/src/main/proto/google_auth.proto) and I have confirmed that works.

**Comment by constantoine** [comment]
Hi! I am trying to understand what the scenario for a migration would be like here, would you be willing to give some kind of user story behind this?

**Comment by constantoine** [comment]
Update: found resources for this [here](https://alexbakker.me/post/parsing-google-auth-export-qr-code.html)

Having to parse a proto message defo seems pretty heavy addition. I can now see the eventual demand, but this seems like possibly quite a bit of additional dependency for something that could be done outside of the scope of this lib
